[package]
name = "Malmmodore_64"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "=0.7.3"
sdl2 = { version = "0.35.2", features = ["use-pkgconfig"] }
lazy_static="1.4.0"
time="0.3.30"