#[derive(Debug)]
pub enum OpMode {
   Implied,
   Immediate,
   Absolute,
   AbsoluteX,
   AbsoluteY,
   Indirect,
   IndirectX,
   IndirectY,
   ZeroPage,
   ZeroPageX,
   ZeroPageY,
   Accumulator,
   Relative,
}

pub struct Opcode {
   pub mnemonic: &'static str,
   pub code: u8,
   pub mode: OpMode,
   pub bytes: u8,
   pub cycles: u8
}

pub fn get_opcode<'a>(code: u8) -> Option<&'a Opcode> {
   match OPCODE.iter().find(|op| op.code == code) {
      Some(val) => Some(val),
      None => None,
   }
}

static OPCODE: [Opcode; 151] = [
   Opcode {
      mnemonic: "BRK",
      code: 0x00,
      mode: OpMode::Implied,
      bytes: 1,
      cycles: 7,
   },
   Opcode {
      mnemonic: "ORA",
      code: 0x01,
      mode: OpMode::IndirectX,
      bytes: 2,
      cycles: 6,
   },
   Opcode {
      mnemonic: "ORA",
      code: 0x05,
      mode: OpMode::ZeroPage,
      bytes: 2,
      cycles: 3,
   },
   Opcode {
      mnemonic: "ASL",
      code: 0x06,
      mode: OpMode::ZeroPage,
      bytes: 2,
      cycles: 5,
   },
   Opcode {
      mnemonic: "PHP",
      code: 0x08,
      mode: OpMode::Implied,
      bytes: 1,
      cycles: 3,
   },
   Opcode {
      mnemonic: "ORA",
      code: 0x09,
      mode: OpMode::Immediate,
      bytes: 2,
      cycles: 2,
   },
   Opcode {
      mnemonic: "ASL",
      code: 0x0A,
      mode: OpMode::Accumulator,
      bytes: 1,
      cycles: 2,
   },
   Opcode {
      mnemonic: "ORA",
      code: 0x0D,
      mode: OpMode::Absolute,
      bytes: 3,
      cycles: 4,
   },
   Opcode {
      mnemonic: "ASL",
      code: 0x0E,
      mode: OpMode::Absolute,
      bytes: 3,
      cycles: 6,
   },
   Opcode {
      mnemonic: "BPL",
      code: 0x10,
      mode: OpMode::Relative,
      bytes: 2,
      cycles: 2,
   },
   Opcode {
      mnemonic: "ORA",
      code: 0x11,
      mode: OpMode::IndirectY,
      bytes: 2,
      cycles: 5,
   },
   Opcode {
      mnemonic: "ORA",
      code: 0x15,
      mode: OpMode::ZeroPageX,
      bytes: 2,
      cycles: 4,
   },
   Opcode {
      mnemonic: "ASL",
      code: 0x16,
      mode: OpMode::ZeroPageX,
      bytes: 2,
      cycles: 6,
   },
   Opcode {
      mnemonic: "CLC",
      code: 0x18,
      mode: OpMode::Implied,
      bytes: 1,
      cycles: 2,
   },
   Opcode {
      mnemonic: "ORA",
      code: 0x19,
      mode: OpMode::AbsoluteY,
      bytes: 3,
      cycles: 4,
   },
   Opcode {
      mnemonic: "ORA",
      code: 0x1D,
      mode: OpMode::AbsoluteX,
      bytes: 3,
      cycles: 4,
   },
   Opcode {
      mnemonic: "ASL",
      code: 0x1E,
      mode: OpMode::AbsoluteX,
      bytes: 3,
      cycles: 7,
   },
   Opcode {
      mnemonic: "JSR",
      code: 0x20,
      mode: OpMode::Absolute,
      bytes: 3,
      cycles: 6,
   },
   Opcode {
      mnemonic: "AND",
      code: 0x21,
      mode: OpMode::IndirectX,
      bytes: 2,
      cycles: 6,
   },
   Opcode {
      mnemonic: "BIT",
      code: 0x24,
      mode: OpMode::ZeroPage,
      bytes: 2,
      cycles: 3,
   },
   Opcode {
      mnemonic: "AND",
      code: 0x25,
      mode: OpMode::ZeroPage,
      bytes: 2,
      cycles: 3,
   },
   Opcode {
      mnemonic: "ROL",
      code: 0x26,
      mode: OpMode::ZeroPage,
      bytes: 2,
      cycles: 5,
   },
   Opcode {
      mnemonic: "PLP",
      code: 0x28,
      mode: OpMode::Implied,
      bytes: 1,
      cycles: 4,
   },
   Opcode {
      mnemonic: "AND",
      code: 0x29,
      mode: OpMode::Immediate,
      bytes: 2,
      cycles: 2,
   },
   Opcode {
      mnemonic: "ROL",
      code: 0x2A,
      mode: OpMode::Accumulator,
      bytes: 1,
      cycles: 2,
   },
   Opcode {
      mnemonic: "BIT",
      code: 0x2C,
      mode: OpMode::Absolute,
      bytes: 3,
      cycles: 4,
   },
   Opcode {
      mnemonic: "AND",
      code: 0x2D,
      mode: OpMode::Absolute,
      bytes: 3,
      cycles: 4,
   },
   Opcode {
      mnemonic: "ROL",
      code: 0x2E,
      mode: OpMode::Absolute,
      bytes: 3,
      cycles: 6,
   },
   Opcode {
      mnemonic: "BMI",
      code: 0x30,
      mode: OpMode::Relative,
      bytes: 2,
      cycles: 2,
   },
   Opcode {
      mnemonic: "AND",
      code: 0x31,
      mode: OpMode::IndirectY,
      bytes: 2,
      cycles: 5,
   },
   Opcode {
      mnemonic: "AND",
      code: 0x35,
      mode: OpMode::ZeroPageX,
      bytes: 2,
      cycles: 4,
   },
   Opcode {
      mnemonic: "ROL",
      code: 0x36,
      mode: OpMode::ZeroPageX,
      bytes: 2,
      cycles: 6,
   },
   Opcode {
      mnemonic: "SEC",
      code: 0x38,
      mode: OpMode::Implied,
      bytes: 1,
      cycles: 2,
   },
   Opcode {
      mnemonic: "AND",
      code: 0x39,
      mode: OpMode::AbsoluteY,
      bytes: 3,
      cycles: 4,
   },
   Opcode {
      mnemonic: "AND",
      code: 0x3D,
      mode: OpMode::AbsoluteX,
      bytes: 3,
      cycles: 4,
   },
   Opcode {
      mnemonic: "ROL",
      code: 0x3E,
      mode: OpMode::AbsoluteX,
      bytes: 3,
      cycles: 7,
   },
   Opcode {
      mnemonic: "RTI",
      code: 0x40,
      mode: OpMode::Implied,
      bytes: 1,
      cycles: 6,
   },
   Opcode {
      mnemonic: "EOR",
      code: 0x41,
      mode: OpMode::IndirectX,
      bytes: 2,
      cycles: 6,
   },
   Opcode {
      mnemonic: "EOR",
      code: 0x45,
      mode: OpMode::ZeroPage,
      bytes: 2,
      cycles: 3,
   },
   Opcode {
      mnemonic: "LSR",
      code: 0x46,
      mode: OpMode::ZeroPage,
      bytes: 2,
      cycles: 5,
   },
   Opcode {
      mnemonic: "PHA",
      code: 0x48,
      mode: OpMode::Implied,
      bytes: 1,
      cycles: 3,
   },
   Opcode {
      mnemonic: "EOR",
      code: 0x49,
      mode: OpMode::Immediate,
      bytes: 2,
      cycles: 2,
   },
   Opcode {
      mnemonic: "LSR",
      code: 0x4A,
      mode: OpMode::Accumulator,
      bytes: 1,
      cycles: 2,
   },
   Opcode {
      mnemonic: "JMP",
      code: 0x4C,
      mode: OpMode::Absolute,
      bytes: 3,
      cycles: 3,
   },
   Opcode {
      mnemonic: "EOR",
      code: 0x4D,
      mode: OpMode::Absolute,
      bytes: 3,
      cycles: 4,
   },
   Opcode {
      mnemonic: "LSR",
      code: 0x4E,
      mode: OpMode::Absolute,
      bytes: 3,
      cycles: 6,
   },
   Opcode {
      mnemonic: "BVC",
      code: 0x50,
      mode: OpMode::Relative,
      bytes: 2,
      cycles: 2,
   },
   Opcode {
      mnemonic: "EOR",
      code: 0x51,
      mode: OpMode::IndirectY,
      bytes: 2,
      cycles: 5,
   },
   Opcode {
      mnemonic: "EOR",
      code: 0x55,
      mode: OpMode::ZeroPageX,
      bytes: 2,
      cycles: 4,
   },
   Opcode {
      mnemonic: "LSR",
      code: 0x56,
      mode: OpMode::ZeroPageX,
      bytes: 2,
      cycles: 6,
   },
   Opcode {
      mnemonic: "CLI",
      code: 0x58,
      mode: OpMode::Implied,
      bytes: 1,
      cycles: 2,
   },
   Opcode {
      mnemonic: "EOR",
      code: 0x59,
      mode: OpMode::AbsoluteY,
      bytes: 3,
      cycles: 4,
   },
   Opcode {
      mnemonic: "EOR",
      code: 0x5D,
      mode: OpMode::AbsoluteX,
      bytes: 3,
      cycles: 4,
   },
   Opcode {
      mnemonic: "LSR",
      code: 0x5E,
      mode: OpMode::AbsoluteX,
      bytes: 3,
      cycles: 7,
   },
   Opcode {
      mnemonic: "RTS",
      code: 0x60,
      mode: OpMode::Implied,
      bytes: 1,
      cycles: 6,
   },
   Opcode {
      mnemonic: "ADC",
      code: 0x61,
      mode: OpMode::IndirectX,
      bytes: 2,
      cycles: 6,
   },
   Opcode {
      mnemonic: "ADC",
      code: 0x65,
      mode: OpMode::ZeroPage,
      bytes: 2,
      cycles: 3,
   },
   Opcode {
      mnemonic: "ROR",
      code: 0x66,
      mode: OpMode::ZeroPage,
      bytes: 2,
      cycles: 5,
   },
   Opcode {
      mnemonic: "PLA",
      code: 0x68,
      mode: OpMode::Implied,
      bytes: 1,
      cycles: 4,
   },
   Opcode {
      mnemonic: "ADC",
      code: 0x69,
      mode: OpMode::Immediate,
      bytes: 2,
      cycles: 2,
   },
   Opcode {
      mnemonic: "ROR",
      code: 0x6A,
      mode: OpMode::Accumulator,
      bytes: 1,
      cycles: 2,
   },
   Opcode {
      mnemonic: "JMP",
      code: 0x6C,
      mode: OpMode::Indirect,
      bytes: 3,
      cycles: 5,
   },
   Opcode {
      mnemonic: "ADC",
      code: 0x6D,
      mode: OpMode::Absolute,
      bytes: 3,
      cycles: 4,
   },
   Opcode {
      mnemonic: "ROR",
      code: 0x6E,
      mode: OpMode::Absolute,
      bytes: 3,
      cycles: 6,
   },
   Opcode {
      mnemonic: "BVS",
      code: 0x70,
      mode: OpMode::Relative,
      bytes: 2,
      cycles: 2,
   },
   Opcode {
      mnemonic: "ADC",
      code: 0x71,
      mode: OpMode::IndirectY,
      bytes: 2,
      cycles: 5,
   },
   Opcode {
      mnemonic: "ADC",
      code: 0x75,
      mode: OpMode::ZeroPageX,
      bytes: 2,
      cycles: 4,
   },
   Opcode {
      mnemonic: "ROR",
      code: 0x76,
      mode: OpMode::ZeroPageX,
      bytes: 2,
      cycles: 6,
   },
   Opcode {
      mnemonic: "SEI",
      code: 0x78,
      mode: OpMode::Implied,
      bytes: 1,
      cycles: 2,
   },
   Opcode {
      mnemonic: "ADC",
      code: 0x79,
      mode: OpMode::AbsoluteY,
      bytes: 3,
      cycles: 4,
   },
   Opcode {
      mnemonic: "ADC",
      code: 0x7D,
      mode: OpMode::AbsoluteX,
      bytes: 3,
      cycles: 4,
   },
   Opcode {
      mnemonic: "ROR",
      code: 0x7E,
      mode: OpMode::AbsoluteX,
      bytes: 3,
      cycles: 7,
   },
   Opcode {
      mnemonic: "STA",
      code: 0x81,
      mode: OpMode::IndirectX,
      bytes: 2,
      cycles: 6,
   },
   Opcode {
      mnemonic: "STY",
      code: 0x84,
      mode: OpMode::ZeroPage,
      bytes: 2,
      cycles: 3,
   },
   Opcode {
      mnemonic: "STA",
      code: 0x85,
      mode: OpMode::ZeroPage,
      bytes: 2,
      cycles: 3,
   },
   Opcode {
      mnemonic: "STX",
      code: 0x86,
      mode: OpMode::ZeroPage,
      bytes: 2,
      cycles: 3,
   },
   Opcode {
      mnemonic: "DEY",
      code: 0x88,
      mode: OpMode::Implied,
      bytes: 1,
      cycles: 2,
   },
   Opcode {
      mnemonic: "TXA",
      code: 0x8A,
      mode: OpMode::Implied,
      bytes: 1,
      cycles: 2,
   },
   Opcode {
      mnemonic: "STY",
      code: 0x8C,
      mode: OpMode::Absolute,
      bytes: 3,
      cycles: 4,
   },
   Opcode {
      mnemonic: "STA",
      code: 0x8D,
      mode: OpMode::Absolute,
      bytes: 3,
      cycles: 4,
   },
   Opcode {
      mnemonic: "STX",
      code: 0x8E,
      mode: OpMode::Absolute,
      bytes: 3,
      cycles: 4,
   },
   Opcode {
      mnemonic: "BCC",
      code: 0x90,
      mode: OpMode::Relative,
      bytes: 2,
      cycles: 2,
   },
   Opcode {
      mnemonic: "STA",
      code: 0x91,
      mode: OpMode::IndirectY,
      bytes: 2,
      cycles: 6,
   },
   Opcode {
      mnemonic: "STY",
      code: 0x94,
      mode: OpMode::ZeroPageX,
      bytes: 2,
      cycles: 4,
   },
   Opcode {
      mnemonic: "STA",
      code: 0x95,
      mode: OpMode::ZeroPageX,
      bytes: 2,
      cycles: 3,
   },
   Opcode {
      mnemonic: "STX",
      code: 0x96,
      mode: OpMode::ZeroPageY,
      bytes: 2,
      cycles: 4,
   },
   Opcode {
      mnemonic: "TYA",
      code: 0x98,
      mode: OpMode::Implied,
      bytes: 1,
      cycles: 2,
   },
   Opcode {
      mnemonic: "STA",
      code: 0x99,
      mode: OpMode::AbsoluteY,
      bytes: 3,
      cycles: 5,
   },
   Opcode {
      mnemonic: "TXS",
      code: 0x9A,
      mode: OpMode::Implied,
      bytes: 1,
      cycles: 2,
   },
   Opcode {
      mnemonic: "STA",
      code: 0x9D,
      mode: OpMode::AbsoluteX,
      bytes: 3,
      cycles: 5,
   },
   Opcode {
      mnemonic: "LDY",
      code: 0xA0,
      mode: OpMode::Immediate,
      bytes: 2,
      cycles: 2,
   },
   Opcode {
      mnemonic: "LDA",
      code: 0xA1,
      mode: OpMode::IndirectX,
      bytes: 2,
      cycles: 6,
   },
   Opcode {
      mnemonic: "LDX",
      code: 0xA2,
      mode: OpMode::Immediate,
      bytes: 2,
      cycles: 2,
   },
   Opcode {
      mnemonic: "LDY",
      code: 0xA4,
      mode: OpMode::ZeroPage,
      bytes: 2,
      cycles: 3,
   },
   Opcode {
      mnemonic: "LDA",
      code: 0xA5,
      mode: OpMode::ZeroPage,
      bytes: 2,
      cycles: 3,
   },
   Opcode {
      mnemonic: "LDX",
      code: 0xA6,
      mode: OpMode::ZeroPage,
      bytes: 2,
      cycles: 3,
   },
   Opcode {
      mnemonic: "TAY",
      code: 0xA8,
      mode: OpMode::Implied,
      bytes: 1,
      cycles: 2,
   },
   Opcode {
      mnemonic: "LDA",
      code: 0xA9,
      mode: OpMode::Immediate,
      bytes: 2,
      cycles: 2,
   },
   Opcode {
      mnemonic: "TAX",
      code: 0xAA,
      mode: OpMode::Implied,
      bytes: 1,
      cycles: 2,
   },
   Opcode {
      mnemonic: "LDY",
      code: 0xAC,
      mode: OpMode::Absolute,
      bytes: 3,
      cycles: 4,
   },
   Opcode {
      mnemonic: "LDA",
      code: 0xAD,
      mode: OpMode::Absolute,
      bytes: 3,
      cycles: 4,
   },
   Opcode {
      mnemonic: "LDX",
      code: 0xAE,
      mode: OpMode::Absolute,
      bytes: 3,
      cycles: 4,
   },
   Opcode {
      mnemonic: "BCS",
      code: 0xB0,
      mode: OpMode::Relative,
      bytes: 2,
      cycles: 2,
   },
   Opcode {
      mnemonic: "LDA",
      code: 0xB1,
      mode: OpMode::IndirectY,
      bytes: 2,
      cycles: 5,
   },
   Opcode {
      mnemonic: "LDY",
      code: 0xB4,
      mode: OpMode::ZeroPageX,
      bytes: 2,
      cycles: 4,
   },
   Opcode {
      mnemonic: "LDA",
      code: 0xB5,
      mode: OpMode::ZeroPageX,
      bytes: 2,
      cycles: 4,
   },
   Opcode {
      mnemonic: "LDX",
      code: 0xB6,
      mode: OpMode::ZeroPageY,
      bytes: 2,
      cycles: 4,
   },
   Opcode {
      mnemonic: "CLV",
      code: 0xB8,
      mode: OpMode::Implied,
      bytes: 1,
      cycles: 2,
   },
   Opcode {
      mnemonic: "LDA",
      code: 0xB9,
      mode: OpMode::AbsoluteY,
      bytes: 3,
      cycles: 4,
   },
   Opcode {
      mnemonic: "TSX",
      code: 0xBA,
      mode: OpMode::Implied,
      bytes: 1,
      cycles: 2,
   },
   Opcode {
      mnemonic: "LDY",
      code: 0xBC,
      mode: OpMode::AbsoluteX,
      bytes: 3,
      cycles: 4,
   },
   Opcode {
      mnemonic: "LDA",
      code: 0xBD,
      mode: OpMode::AbsoluteX,
      bytes: 3,
      cycles: 4,
   },
   Opcode {
      mnemonic: "LDX",
      code: 0xBE,
      mode: OpMode::AbsoluteY,
      bytes: 3,
      cycles: 4,
   },
   Opcode {
      mnemonic: "CPY",
      code: 0xC0,
      mode: OpMode::Immediate,
      bytes: 2,
      cycles: 2,
   },
   Opcode {
      mnemonic: "CMP",
      code: 0xC1,
      mode: OpMode::IndirectX,
      bytes: 2,
      cycles: 6,
   },
   Opcode {
      mnemonic: "CPY",
      code: 0xC4,
      mode: OpMode::ZeroPage,
      bytes: 2,
      cycles: 3,
   },
   Opcode {
      mnemonic: "CMP",
      code: 0xC5,
      mode: OpMode::ZeroPage,
      bytes: 2,
      cycles: 3,
   },
   Opcode {
      mnemonic: "DEC",
      code: 0xC6,
      mode: OpMode::ZeroPage,
      bytes: 2,
      cycles: 5,
   },
   Opcode {
      mnemonic: "INY",
      code: 0xC8,
      mode: OpMode::Implied,
      bytes: 1,
      cycles: 2,
   },
   Opcode {
      mnemonic: "CMP",
      code: 0xC9,
      mode: OpMode::Immediate,
      bytes: 2,
      cycles: 2,
   },
   Opcode {
      mnemonic: "DEX",
      code: 0xCA,
      mode: OpMode::Implied,
      bytes: 1,
      cycles: 2,
   },
   Opcode {
      mnemonic: "CPY",
      code: 0xCC,
      mode: OpMode::Absolute,
      bytes: 3,
      cycles: 4,
   },
   Opcode {
      mnemonic: "CMP",
      code: 0xCD,
      mode: OpMode::Absolute,
      bytes: 3,
      cycles: 4,
   },
   Opcode {
      mnemonic: "DEC",
      code: 0xCE,
      mode: OpMode::Absolute,
      bytes: 3,
      cycles: 6,
   },
   Opcode {
      mnemonic: "BNE",
      code: 0xD0,
      mode: OpMode::Relative,
      bytes: 2,
      cycles: 2,
   },
   Opcode {
      mnemonic: "CMP",
      code: 0xD1,
      mode: OpMode::IndirectY,
      bytes: 2,
      cycles: 5,
   },
   Opcode {
      mnemonic: "CMP",
      code: 0xD5,
      mode: OpMode::ZeroPageX,
      bytes: 2,
      cycles: 4,
   },
   Opcode {
      mnemonic: "DEC",
      code: 0xD6,
      mode: OpMode::ZeroPageX,
      bytes: 2,
      cycles: 6,
   },
   Opcode {
      mnemonic: "CLD",
      code: 0xD8,
      mode: OpMode::Implied,
      bytes: 1,
      cycles: 2,
   },
   Opcode {
      mnemonic: "CMP",
      code: 0xD9,
      mode: OpMode::AbsoluteY,
      bytes: 3,
      cycles: 4,
   },
   Opcode {
      mnemonic: "CMP",
      code: 0xDD,
      mode: OpMode::AbsoluteX,
      bytes: 3,
      cycles: 4,
   },
   Opcode {
      mnemonic: "DEC",
      code: 0xDE,
      mode: OpMode::AbsoluteX,
      bytes: 3,
      cycles: 7,
   },
   Opcode {
      mnemonic: "CPX",
      code: 0xE0,
      mode: OpMode::Immediate,
      bytes: 2,
      cycles: 2,
   },
   Opcode {
      mnemonic: "SBC",
      code: 0xE1,
      mode: OpMode::IndirectX,
      bytes: 2,
      cycles: 6,
   },
   Opcode {
      mnemonic: "CPX",
      code: 0xE4,
      mode: OpMode::ZeroPage,
      bytes: 2,
      cycles: 3,
   },
   Opcode {
      mnemonic: "SBC",
      code: 0xE5,
      mode: OpMode::ZeroPage,
      bytes: 2,
      cycles: 3,
   },
   Opcode {
      mnemonic: "INC",
      code: 0xE6,
      mode: OpMode::ZeroPage,
      bytes: 2,
      cycles: 5,
   },
   Opcode {
      mnemonic: "INX",
      code: 0xE8,
      mode: OpMode::Implied,
      bytes: 1,
      cycles: 2,
   },
   Opcode {
      mnemonic: "SBC",
      code: 0xE9,
      mode: OpMode::Immediate,
      bytes: 2,
      cycles: 2,
   },
   Opcode {
      mnemonic: "NOP",
      code: 0xEA,
      mode: OpMode::Implied,
      bytes: 1,
      cycles: 2,
   },
   Opcode {
      mnemonic: "CPX",
      code: 0xEC,
      mode: OpMode::Absolute,
      bytes: 3,
      cycles: 4,
   },
   Opcode {
      mnemonic: "SBC",
      code: 0xED,
      mode: OpMode::Absolute,
      bytes: 3,
      cycles: 4,
   },
   Opcode {
      mnemonic: "INC",
      code: 0xEE,
      mode: OpMode::Absolute,
      bytes: 3,
      cycles: 6,
   },
   Opcode {
      mnemonic: "BEQ",
      code: 0xF0,
      mode: OpMode::Relative,
      bytes: 2,
      cycles: 2,
   },
   Opcode {
      mnemonic: "SBC",
      code: 0xF1,
      mode: OpMode::IndirectY,
      bytes: 2,
      cycles: 5,
   },
   Opcode {
      mnemonic: "SBC",
      code: 0xF5,
      mode: OpMode::ZeroPageX,
      bytes: 2,
      cycles: 4,
   },
   Opcode {
      mnemonic: "INC",
      code: 0xF6,
      mode: OpMode::ZeroPageX,
      bytes: 2,
      cycles: 6,
   },
   Opcode {
      mnemonic: "SED",
      code: 0xF8,
      mode: OpMode::Implied,
      bytes: 1,
      cycles: 2,
   },
   Opcode {
      mnemonic: "SBC",
      code: 0xF9,
      mode: OpMode::AbsoluteY,
      bytes: 3,
      cycles: 4,
   },
   Opcode {
      mnemonic: "SBC",
      code: 0xFD,
      mode: OpMode::AbsoluteX,
      bytes: 3,
      cycles: 4,
   },
   Opcode {
      mnemonic: "INC",
      code: 0xFE,
      mode: OpMode::AbsoluteX,
      bytes: 3,
      cycles: 7,
   },
];